#!/usr/bin/python

#
# Original input files in the source tree.
#

js_in_files = (
  'init.js',
  'src/shared/js/cr.js',
  'src/shared/js/cr/event_target.js',
  'src/shared/js/cr/ui.js',
  'src/shared/js/cr/ui/focus_outline_manager.js',
  'src/shared/js/cr/ui/tabs.js',
  'src/shared/js/util.js',
  'src/tracing/overlay.js',
  'src/tracing/tracing_controller.js',
  'src/tracing/timeline_model.js',
  'src/tracing/linux_perf_importer.js',
  'src/tracing/trace_event_importer.js',
  'src/tracing/sorted_array_utils.js',
  'src/tracing/measuring_stick.js',
  'src/tracing/timeline.js',
  'src/tracing/timeline_analysis.js',
  'src/tracing/timeline_track.js',
  'src/tracing/fast_rect_renderer.js',
  'src/tracing/profiling_view.js',
  'src/tracing/timeline_view.js',
)

css_in_files = (
  'src/shared/css/tabs.css',
  'src/shared/css/widgets.css',
  'src/tracing/overlay.css',
  'src/tracing/profiling_view.css',
  'src/tracing/timeline_analysis.css',
  'src/tracing/timeline_view.css',
  'src/tracing/timeline.css',
  'src/tracing/tracing_controller.css',
)

#
# Compiled output files generated by update.py.
#

js_out_file = 'script.js'

css_out_file = 'style.css'
